INSERT INTO accounts(username, password, role, enabled, invaliddate) VALUES('testuser', '$2a$10$R/jnN6upwT4bLNGEvQTHYOVE.cDXxGpHTs5IAs1hbeOrO.PuGMI02', 'ADMIN', true, '2025-09-16');
INSERT INTO accounts(username, password, role, enabled, invaliddate) VALUES('testuser2', '$2a$10$R/jnN6upwT4bLNGEvQTHYOVE.cDXxGpHTs5IAs1hbeOrO.PuGMI02', 'GENERAL', true, '2024-10-16');
INSERT INTO accounts(username, password, role, enabled, invaliddate) VALUES('testuser3', '$2a$10$R/jnN6upwT4bLNGEvQTHYOVE.cDXxGpHTs5IAs1hbeOrO.PuGMI02', 'GENERAL', true, '2024-09-16');

INSERT INTO item(id, itemname, price, itemdescription) VALUES(1, 'item name1', 1000, 'item description1');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(2, 'item name2', 1000, 'item description2');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(3, 'item name3', 1000, 'item description3');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(4, 'item name4', 1000, 'item description4');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(5, 'item name5', 1000, 'item description5');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(6, 'item name6', 1000, 'item description6');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(7, 'item name7', 1000, 'item description7');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(8, 'item name8', 1000, 'item description8');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(9, 'item name9', 1000, 'item description9');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(10, 'item name10', 1000, 'item description10');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(11, 'item name11', 1000, 'item description11');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(12, 'item name12', 1000, 'item description12');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(13, 'item name13', 1000, 'item description13');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(14, 'item name14', 1000, 'item description14');
INSERT INTO item(id, itemname, price, itemdescription) VALUES(15, 'item name15', 1000, 'item description15');